import type { Payload } from 'payload'

export const toursData = [
  {
    title: '7-Day Maasai Mara Great Migration Safari',
    slug: '7-day-maasai-mara-great-migration-safari',
    shortDescription: 'Witness the world\'s greatest wildlife spectacle – over 2 million wildebeest crossing the Mara River. An unforgettable Kenya safari with luxury tented camps and expert guides.',
    tourType: 'wildlife-safari',
    countries: ['kenya'],
    duration: 7,
    price: { amount: 3200, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 2, max: 8 },
    difficulty: 'easy',
    bestTime: 'July to October',
    isFeatured: true,
    isPopular: true,
    availability: 'jul-sep',
    highlights: [
      { highlight: 'Witness the Great Wildebeest Migration river crossings' },
      { highlight: 'Daily game drives in Maasai Mara National Reserve' },
      { highlight: 'Big Five sightings: lion, elephant, buffalo, leopard, rhino' },
      { highlight: 'Luxury tented camp accommodation with full board' },
      { highlight: 'Maasai village cultural visit' },
      { highlight: 'Optional hot air balloon safari at sunrise' },
    ],
    faqs: [
      { question: 'When is the best time to see the Great Migration?', answer: 'The peak river crossing season is July to October. The wildebeest are in the Maasai Mara from approximately July through November.' },
      { question: 'What is included in the safari price?', answer: 'All game drives, accommodation (full board), park fees, airport transfers, and professional guide services are included.' },
      { question: 'What wildlife will I see?', answer: 'The Maasai Mara hosts the Big Five (lion, leopard, elephant, buffalo, rhino) plus cheetah, zebra, giraffe, hippo, crocodile, and hundreds of bird species.' },
    ],
    keywords: [
      { keyword: 'Great Migration safari Kenya', searchVolume: 'high' },
      { keyword: 'Maasai Mara safari', searchVolume: 'high' },
      { keyword: 'wildebeest migration tour', searchVolume: 'high' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '1.0',
      sitemapChangefreq: 'weekly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList', 'AggregateRating'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: '7-Day Maasai Mara Great Migration Safari', url: '/tours/7-day-maasai-mara-great-migration-safari' },
      ],
    },
  },
  {
    title: '8-Day Gorilla Trekking Rwanda & Golden Monkey Tour',
    slug: '8-day-gorilla-trekking-rwanda-golden-monkey',
    shortDescription: 'Trek through Volcanoes National Park to encounter endangered mountain gorillas face-to-face. Combine gorilla trekking with golden monkey tracking in this extraordinary Rwanda adventure.',
    tourType: 'gorilla-trekking',
    countries: ['rwanda'],
    duration: 8,
    price: { amount: 4800, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 2, max: 8 },
    difficulty: 'moderate',
    bestTime: 'June to September, December to February',
    isFeatured: true,
    isPopular: true,
    availability: 'year-round',
    highlights: [
      { highlight: 'Mountain gorilla trekking permit in Volcanoes National Park' },
      { highlight: 'Golden monkey tracking in bamboo forests' },
      { highlight: 'One full hour with a gorilla family in their natural habitat' },
      { highlight: 'Visit the Dian Fossey Gorilla Fund research center' },
      { highlight: 'Twin Lakes (Burera & Ruhondo) boat trip' },
      { highlight: 'Kigali Genocide Memorial cultural visit' },
    ],
    faqs: [
      { question: 'How difficult is gorilla trekking?', answer: 'Gorilla trekking is rated moderate to challenging. You may hike 2-8 hours through steep volcanic terrain. Good physical fitness is required.' },
      { question: 'How much does a gorilla permit cost?', answer: 'Rwanda gorilla permits cost $1,500 USD per person per trek. This is included in our tour price.' },
      { question: 'How close do you get to gorillas?', answer: 'You spend exactly one hour within 7 meters of a habituated gorilla family. This is strictly enforced to protect both gorillas and visitors.' },
    ],
    keywords: [
      { keyword: 'gorilla trekking Rwanda', searchVolume: 'high' },
      { keyword: 'mountain gorilla safari', searchVolume: 'high' },
      { keyword: 'Rwanda gorilla tour', searchVolume: 'high' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '1.0',
      sitemapChangefreq: 'weekly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList', 'AggregateRating'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Gorilla Trekking Rwanda', url: '/tours/8-day-gorilla-trekking-rwanda-golden-monkey' },
      ],
    },
  },
  {
    title: '9-Day Kilimanjaro Climb via Lemosho Route',
    slug: '9-day-kilimanjaro-climb-lemosho-route',
    shortDescription: 'Conquer Africa\'s highest peak via the scenic Lemosho Route. The 9-day itinerary offers the highest acclimatization success rate (85%+) for reaching Uhuru Peak at 5,895m.',
    tourType: 'mountain-trekking',
    countries: ['tanzania'],
    duration: 9,
    price: { amount: 2800, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 1, max: 10 },
    difficulty: 'strenuous',
    bestTime: 'January to March, June to October',
    isFeatured: true,
    isPopular: true,
    availability: 'year-round',
    highlights: [
      { highlight: 'Summit Uhuru Peak at 5,895m – Roof of Africa' },
      { highlight: '85%+ summit success rate with 9-day acclimatization' },
      { highlight: 'Lemosho Route – most scenic and least crowded' },
      { highlight: 'Experienced certified mountain guides and porters' },
      { highlight: 'All camping equipment, meals and rescue insurance included' },
      { highlight: 'Certificate of summit achievement' },
    ],
    faqs: [
      { question: 'Do I need prior mountaineering experience?', answer: 'No technical climbing skills are needed. However, you should be physically fit and able to hike 6-8 hours daily carrying a daypack.' },
      { question: 'What is the success rate?', answer: 'Our 9-day Lemosho Route has an 85%+ summit success rate, significantly higher than the popular 6-day Marangu route (45%).' },
      { question: 'What gear do I need?', answer: 'We provide a full gear list on booking. Key items include warm layers for summit night (-10°C to -20°C), trekking poles, and quality hiking boots.' },
    ],
    keywords: [
      { keyword: 'Kilimanjaro climb', searchVolume: 'high' },
      { keyword: 'Kilimanjaro Lemosho route', searchVolume: 'medium' },
      { keyword: 'Mount Kilimanjaro trek', searchVolume: 'high' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '1.0',
      sitemapChangefreq: 'weekly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList', 'AggregateRating'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Kilimanjaro Lemosho Route', url: '/tours/9-day-kilimanjaro-climb-lemosho-route' },
      ],
    },
  },
  {
    title: '6-Day Serengeti Safari & Ngorongoro Crater Tour',
    slug: '6-day-serengeti-ngorongoro-crater-safari',
    shortDescription: 'Explore Tanzania\'s crown jewels: the endless Serengeti plains teeming with wildlife and the UNESCO World Heritage Ngorongoro Crater – the world\'s largest intact volcanic caldera.',
    tourType: 'wildlife-safari',
    countries: ['tanzania'],
    duration: 6,
    price: { amount: 2600, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 2, max: 8 },
    difficulty: 'easy',
    bestTime: 'January to March, June to October',
    isFeatured: true,
    isPopular: true,
    availability: 'year-round',
    highlights: [
      { highlight: 'Game drives in the world-famous Serengeti National Park' },
      { highlight: 'Descent into Ngorongoro Crater for Big Five viewing' },
      { highlight: 'Witness calving season (Jan-Feb) or Migration (Jun-Oct)' },
      { highlight: 'Olduvai Gorge – cradle of mankind museum visit' },
      { highlight: 'Luxury lodge and tented camp accommodation' },
      { highlight: 'Private 4x4 Land Cruiser with pop-up roof' },
    ],
    faqs: [
      { question: 'What is Ngorongoro Crater?', answer: 'Ngorongoro is the world\'s largest intact volcanic caldera, 19km across. It hosts approximately 25,000 large animals including the highest density of predators in Africa.' },
      { question: 'Can I see lions in the Serengeti?', answer: 'Yes! The Serengeti has the highest concentration of lions in Africa, with over 3,000 lions in the ecosystem.' },
    ],
    keywords: [
      { keyword: 'Serengeti safari', searchVolume: 'high' },
      { keyword: 'Ngorongoro Crater tour', searchVolume: 'high' },
      { keyword: 'Tanzania safari package', searchVolume: 'high' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '1.0',
      sitemapChangefreq: 'weekly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList', 'AggregateRating'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Serengeti & Ngorongoro Safari', url: '/tours/6-day-serengeti-ngorongoro-crater-safari' },
      ],
    },
  },
  {
    title: '10-Day Uganda Gorilla & Chimpanzee Trekking Safari',
    slug: '10-day-uganda-gorilla-chimpanzee-safari',
    shortDescription: 'Track mountain gorillas in Bwindi Impenetrable Forest and wild chimpanzees in Kibale National Park. Uganda offers the best value gorilla permits in East Africa at $700 USD.',
    tourType: 'gorilla-trekking',
    countries: ['uganda'],
    duration: 10,
    price: { amount: 3900, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 2, max: 8 },
    difficulty: 'moderate',
    bestTime: 'June to September, December to February',
    isFeatured: false,
    isPopular: true,
    availability: 'year-round',
    highlights: [
      { highlight: 'Mountain gorilla trekking in Bwindi Impenetrable Forest' },
      { highlight: 'Chimpanzee tracking in Kibale Forest National Park' },
      { highlight: 'Queen Elizabeth National Park game drives & boat cruise' },
      { highlight: 'Tree-climbing lions in Ishasha sector' },
      { highlight: 'Equator crossing photo stop' },
      { highlight: 'Uganda permits: best value at $700 vs Rwanda $1,500' },
    ],
    faqs: [
      { question: 'How do Uganda gorilla permits compare to Rwanda?', answer: 'Uganda gorilla permits cost $700 USD per person, significantly less than Rwanda\'s $1,500. Uganda has half of the world\'s mountain gorillas.' },
      { question: 'What is the best time to trek gorillas in Uganda?', answer: 'The dry seasons (June-September and December-February) offer the best trekking conditions with less muddy trails.' },
    ],
    keywords: [
      { keyword: 'Uganda gorilla trekking', searchVolume: 'high' },
      { keyword: 'Bwindi gorilla safari', searchVolume: 'high' },
      { keyword: 'chimpanzee tracking Uganda', searchVolume: 'medium' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '0.9',
      sitemapChangefreq: 'weekly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Uganda Gorilla & Chimp Safari', url: '/tours/10-day-uganda-gorilla-chimpanzee-safari' },
      ],
    },
  },
  {
    title: '7-Day Zanzibar Beach & Spice Island Holiday',
    slug: '7-day-zanzibar-beach-spice-island-holiday',
    shortDescription: 'Unwind on Zanzibar\'s powder-white beaches after your safari. Explore the UNESCO Stone Town, swim with dolphins, snorkel coral reefs, and tour the famous spice plantations.',
    tourType: 'beach-island',
    countries: ['zanzibar'],
    duration: 7,
    price: { amount: 1800, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 2, max: 12 },
    difficulty: 'easy',
    bestTime: 'June to October, December to February',
    isFeatured: false,
    isPopular: true,
    availability: 'year-round',
    highlights: [
      { highlight: 'Pristine beaches: Nungwi, Kendwa, Paje & Matemwe' },
      { highlight: 'UNESCO World Heritage Stone Town exploration' },
      { highlight: 'Dolphin swimming in Kizimkazi' },
      { highlight: 'Spice plantation tour – cloves, vanilla, cinnamon' },
      { highlight: 'Prison Island giant tortoise visit' },
      { highlight: 'Snorkeling on the coral reef of Mnemba Atoll' },
    ],
    faqs: [
      { question: 'What is the best beach in Zanzibar?', answer: 'Nungwi and Kendwa in the north are best for swimming year-round. Paje on the east coast is ideal for kitesurfing. Matemwe is quieter and more exclusive.' },
      { question: 'Can I combine Zanzibar with a Tanzania safari?', answer: 'Absolutely! Most visitors combine 5-6 days of safari (Serengeti, Ngorongoro) with 7 days in Zanzibar for the perfect "Bush & Beach" holiday.' },
    ],
    keywords: [
      { keyword: 'Zanzibar beach holiday', searchVolume: 'high' },
      { keyword: 'Zanzibar tour packages', searchVolume: 'high' },
      { keyword: 'Stone Town Zanzibar', searchVolume: 'medium' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '0.9',
      sitemapChangefreq: 'weekly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Zanzibar Beach Holiday', url: '/tours/7-day-zanzibar-beach-spice-island-holiday' },
      ],
    },
  },
  {
    title: '5-Day Amboseli Elephant Safari with Kilimanjaro Views',
    slug: '5-day-amboseli-elephant-safari-kilimanjaro-views',
    shortDescription: 'Photograph Africa\'s largest elephant herds against the iconic snow-capped backdrop of Mount Kilimanjaro. Amboseli National Park offers Kenya\'s most dramatic wildlife photography opportunities.',
    tourType: 'wildlife-safari',
    countries: ['kenya'],
    duration: 5,
    price: { amount: 1950, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 2, max: 8 },
    difficulty: 'easy',
    bestTime: 'January to February, June to October',
    isFeatured: false,
    isPopular: false,
    availability: 'year-round',
    highlights: [
      { highlight: 'Massive elephant herds at Amboseli (some of Africa\'s largest tuskers)' },
      { highlight: 'Iconic Kilimanjaro mountain views and photography' },
      { highlight: 'Big Five game viewing and over 400 bird species' },
      { highlight: 'Maasai cultural experience at an authentic village' },
      { highlight: 'Observation Hill sunrise and sunset views' },
      { highlight: 'Visit Kimana Sanctuary – rhino conservation project' },
    ],
    faqs: [
      { question: 'How many elephants are in Amboseli?', answer: 'Amboseli has approximately 1,600 elephants, including some of the largest tuskers in Africa. The elephants are highly studied and very relaxed around vehicles.' },
    ],
    keywords: [
      { keyword: 'Amboseli safari', searchVolume: 'high' },
      { keyword: 'Amboseli elephant tour', searchVolume: 'medium' },
      { keyword: 'Kenya safari Kilimanjaro', searchVolume: 'medium' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '0.8',
      sitemapChangefreq: 'weekly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Amboseli Elephant Safari', url: '/tours/5-day-amboseli-elephant-safari-kilimanjaro-views' },
      ],
    },
  },
  {
    title: '4-Day Masai Mara Hot Air Balloon Safari',
    slug: '4-day-masai-mara-hot-air-balloon-safari',
    shortDescription: 'Soar over the Maasai Mara at dawn in a hot air balloon and watch Africa\'s wildlife from above. Includes luxury tented camp stays and twice-daily game drives.',
    tourType: 'hot-air-balloon',
    countries: ['kenya'],
    duration: 4,
    price: { amount: 2400, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 2, max: 8 },
    difficulty: 'easy',
    bestTime: 'July to October',
    isFeatured: false,
    isPopular: false,
    availability: 'year-round',
    highlights: [
      { highlight: 'Sunrise hot air balloon flight over Maasai Mara' },
      { highlight: 'Champagne bush breakfast after the balloon flight' },
      { highlight: 'Luxury tented camp with en-suite facilities' },
      { highlight: 'Morning and afternoon game drives' },
      { highlight: 'Unique aerial photography opportunities' },
    ],
    faqs: [
      { question: 'Is hot air ballooning safe?', answer: 'Yes. Our balloon operators are fully licensed and have operated flights in the Mara for over 20 years with an excellent safety record.' },
    ],
    keywords: [
      { keyword: 'Maasai Mara hot air balloon safari', searchVolume: 'medium' },
      { keyword: 'Kenya balloon safari', searchVolume: 'medium' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '0.8',
      sitemapChangefreq: 'weekly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Mara Hot Air Balloon Safari', url: '/tours/4-day-masai-mara-hot-air-balloon-safari' },
      ],
    },
  },
  {
    title: '12-Day Kenya & Tanzania Grand Safari',
    slug: '12-day-kenya-tanzania-grand-safari',
    shortDescription: 'The ultimate East Africa grand safari combining Kenya\'s Maasai Mara, Amboseli and Tanzania\'s Serengeti and Ngorongoro Crater in one seamless 12-day adventure.',
    tourType: 'wildlife-safari',
    countries: ['kenya', 'tanzania'],
    duration: 12,
    price: { amount: 5500, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 2, max: 8 },
    difficulty: 'easy',
    bestTime: 'July to October',
    isFeatured: true,
    isPopular: true,
    availability: 'year-round',
    highlights: [
      { highlight: 'Maasai Mara – Great Migration river crossings' },
      { highlight: 'Amboseli – elephants with Kilimanjaro backdrop' },
      { highlight: 'Serengeti – lions, cheetahs and leopards' },
      { highlight: 'Ngorongoro Crater – highest density of predators' },
      { highlight: 'Cross the Kenya-Tanzania border by 4x4' },
      { highlight: 'Mix of luxury lodges and authentic bush camps' },
    ],
    faqs: [
      { question: 'Do I need a visa for both Kenya and Tanzania?', answer: 'Yes. The East Africa Tourist Visa ($100 USD) covers Kenya, Uganda, and Rwanda. Tanzania requires a separate visa ($50 USD) or you can get it on arrival.' },
    ],
    keywords: [
      { keyword: 'Kenya Tanzania safari', searchVolume: 'high' },
      { keyword: 'East Africa safari package', searchVolume: 'high' },
      { keyword: 'grand safari East Africa', searchVolume: 'medium' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '1.0',
      sitemapChangefreq: 'weekly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList', 'AggregateRating'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Kenya Tanzania Grand Safari', url: '/tours/12-day-kenya-tanzania-grand-safari' },
      ],
    },
  },
  {
    title: '6-Day Lake Nakuru & Samburu Wildlife Safari',
    slug: '6-day-lake-nakuru-samburu-wildlife-safari',
    shortDescription: 'Discover Kenya\'s hidden gems: flamingo-pink Lake Nakuru and the remote Samburu Reserve – home to the "Samburu Special Five" species found nowhere else in East Africa.',
    tourType: 'wildlife-safari',
    countries: ['kenya'],
    duration: 6,
    price: { amount: 2100, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 2, max: 8 },
    difficulty: 'easy',
    bestTime: 'Year-round',
    isFeatured: false,
    isPopular: false,
    availability: 'year-round',
    highlights: [
      { highlight: 'Lake Nakuru flamingos and rhino sanctuary' },
      { highlight: 'Samburu Special Five: Reticulated giraffe, Grevy\'s zebra, Somali ostrich, Gerenuk, Beisa oryx' },
      { highlight: 'Ewaso Nyiro River game drives and bird watching' },
      { highlight: 'Remote northern Kenya landscapes' },
      { highlight: 'White rhino protection project' },
    ],
    faqs: [
      { question: 'What are the Samburu Special Five?', answer: 'The Samburu Special Five are wildlife species uniquely found in the Samburu ecosystem: Reticulated giraffe, Grevy\'s zebra, Somali ostrich, Gerenuk antelope, and Beisa oryx.' },
    ],
    keywords: [
      { keyword: 'Lake Nakuru safari', searchVolume: 'medium' },
      { keyword: 'Samburu National Reserve tour', searchVolume: 'medium' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '0.8',
      sitemapChangefreq: 'monthly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Nakuru & Samburu Safari', url: '/tours/6-day-lake-nakuru-samburu-wildlife-safari' },
      ],
    },
  },
  {
    title: '14-Day East Africa Gorillas & Safari Grand Tour',
    slug: '14-day-east-africa-gorillas-safari-grand-tour',
    shortDescription: 'The most comprehensive East Africa adventure: gorilla trekking in Rwanda, chimpanzee tracking in Uganda, plus wildlife safaris in Kenya and Tanzania – all in 14 epic days.',
    tourType: 'gorilla-trekking',
    countries: ['kenya', 'tanzania', 'uganda', 'rwanda'],
    duration: 14,
    price: { amount: 7800, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 2, max: 6 },
    difficulty: 'moderate',
    bestTime: 'June to September',
    isFeatured: true,
    isPopular: false,
    availability: 'year-round',
    highlights: [
      { highlight: 'Mountain gorilla trekking in Rwanda\'s Volcanoes NP' },
      { highlight: 'Chimpanzee tracking in Kibale, Uganda' },
      { highlight: 'Maasai Mara game drives & Great Migration' },
      { highlight: 'Serengeti and Ngorongoro Crater' },
      { highlight: 'Covers 4 countries in one seamless journey' },
      { highlight: 'Premium private guiding throughout' },
    ],
    faqs: [
      { question: 'Is 14 days enough for this grand tour?', answer: 'Yes, 14 days is perfectly paced for this itinerary with internal flights to avoid long drives, allowing you to enjoy each destination without fatigue.' },
    ],
    keywords: [
      { keyword: 'East Africa grand tour', searchVolume: 'medium' },
      { keyword: 'gorilla trekking and safari', searchVolume: 'high' },
      { keyword: 'multi-country Africa tour', searchVolume: 'medium' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '0.9',
      sitemapChangefreq: 'weekly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'East Africa Grand Tour', url: '/tours/14-day-east-africa-gorillas-safari-grand-tour' },
      ],
    },
  },
  {
    title: '10-Day Ethiopia Historical Lalibela & Omo Valley Tour',
    slug: '10-day-ethiopia-lalibela-omo-valley-cultural-tour',
    shortDescription: 'Journey through Ethiopia\'s ancient civilizations: the rock-hewn churches of Lalibela, the castles of Gondar, and the unique tribes of the Omo Valley – Africa\'s most extraordinary cultural safari.',
    tourType: 'cultural-heritage',
    countries: ['ethiopia'],
    duration: 10,
    price: { amount: 3100, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 2, max: 10 },
    difficulty: 'moderate',
    bestTime: 'October to May',
    isFeatured: false,
    isPopular: false,
    availability: 'year-round',
    highlights: [
      { highlight: 'Lalibela rock-hewn churches – 8th Wonder of the World' },
      { highlight: 'Gondar castles – the Camelot of Africa' },
      { highlight: 'Omo Valley tribal cultures: Mursi, Hamar, Karo' },
      { highlight: 'Simien Mountains trekking and gelada baboons' },
      { highlight: 'Axum obelisks and pre-Christian history' },
      { highlight: 'Ethiopian Orthodox religious ceremonies' },
    ],
    faqs: [
      { question: 'Is Ethiopia safe for tourists?', answer: 'The historical northern circuit (Addis Ababa, Lalibela, Gondar, Axum, Simien Mountains) and the Omo Valley are safe for international tourists with a reputable guide.' },
    ],
    keywords: [
      { keyword: 'Ethiopia cultural tour', searchVolume: 'medium' },
      { keyword: 'Lalibela tour', searchVolume: 'medium' },
      { keyword: 'Omo Valley tribes tour', searchVolume: 'medium' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '0.8',
      sitemapChangefreq: 'monthly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Ethiopia Cultural Tour', url: '/tours/10-day-ethiopia-lalibela-omo-valley-cultural-tour' },
      ],
    },
  },
  {
    title: '5-Day Kenya Luxury Safari – Maasai Mara & Laikipia',
    slug: '5-day-kenya-luxury-safari-maasai-mara-laikipia',
    shortDescription: 'The ultimate Kenya luxury safari combining the Maasai Mara with the wild Laikipia Plateau. Stay in award-winning eco-lodges, enjoy private game drives and horse riding with the Big Five.',
    tourType: 'luxury-safari',
    countries: ['kenya'],
    duration: 5,
    price: { amount: 6500, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 2, max: 6 },
    difficulty: 'easy',
    bestTime: 'June to October',
    isFeatured: false,
    isPopular: false,
    availability: 'year-round',
    highlights: [
      { highlight: 'Private game drives in exclusive conservancies' },
      { highlight: 'Horse riding safaris alongside zebra and giraffe' },
      { highlight: 'Walking safaris with Maasai guides' },
      { highlight: 'Award-winning luxury eco-lodge accommodation' },
      { highlight: 'Night game drives – rare nocturnal wildlife' },
      { highlight: 'Helicopter transfers for dramatic aerial views' },
    ],
    faqs: [
      { question: 'What makes Laikipia special?', answer: 'Laikipia Plateau is one of Kenya\'s best-kept secrets. It\'s home to Africa\'s second-largest rhino population, wild dogs, and fewer tourist crowds with exclusive private conservancies.' },
    ],
    keywords: [
      { keyword: 'luxury Kenya safari', searchVolume: 'high' },
      { keyword: 'luxury African safari', searchVolume: 'high' },
      { keyword: 'Laikipia safari', searchVolume: 'medium' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '0.9',
      sitemapChangefreq: 'weekly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Kenya Luxury Safari', url: '/tours/5-day-kenya-luxury-safari-maasai-mara-laikipia' },
      ],
    },
  },
  {
    title: '8-Day Tanzania Tarangire, Manyara & Serengeti Safari',
    slug: '8-day-tanzania-tarangire-manyara-serengeti-safari',
    shortDescription: 'Tanzania\'s Northern Circuit complete: Tarangire\'s massive elephant herds and iconic baobabs, Lake Manyara\'s tree-climbing lions and flamingos, and the Serengeti\'s endless wildlife show.',
    tourType: 'wildlife-safari',
    countries: ['tanzania'],
    duration: 8,
    price: { amount: 3400, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 2, max: 8 },
    difficulty: 'easy',
    bestTime: 'June to October, January to March',
    isFeatured: false,
    isPopular: true,
    availability: 'year-round',
    highlights: [
      { highlight: 'Tarangire National Park – largest elephant herds in Tanzania' },
      { highlight: 'Iconic ancient baobab trees of Tarangire' },
      { highlight: 'Lake Manyara tree-climbing lions' },
      { highlight: 'Serengeti big cat territory and open plains' },
      { highlight: 'Full Northern Circuit in one safari' },
    ],
    faqs: [
      { question: 'What is the Northern Circuit?', answer: 'Tanzania\'s Northern Circuit includes Tarangire, Lake Manyara, Serengeti, and Ngorongoro Crater – the country\'s most popular safari destinations accessible from Arusha.' },
    ],
    keywords: [
      { keyword: 'Tanzania Northern Circuit safari', searchVolume: 'medium' },
      { keyword: 'Tarangire National Park safari', searchVolume: 'medium' },
      { keyword: 'Lake Manyara safari', searchVolume: 'medium' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '0.8',
      sitemapChangefreq: 'weekly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Tanzania Northern Circuit Safari', url: '/tours/8-day-tanzania-tarangire-manyara-serengeti-safari' },
      ],
    },
  },
  {
    title: '6-Day Rwanda Gorillas, Tea Plantations & Kigali City Tour',
    slug: '6-day-rwanda-gorillas-tea-plantations-kigali',
    shortDescription: 'Rwanda in full: gorilla trekking, visit the green tea plantations of Nyungwe, explore Kigali\'s vibrant city and moving genocide memorial, and unwind at Lake Kivu.',
    tourType: 'gorilla-trekking',
    countries: ['rwanda'],
    duration: 6,
    price: { amount: 3200, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 2, max: 8 },
    difficulty: 'moderate',
    bestTime: 'June to September',
    isFeatured: false,
    isPopular: false,
    availability: 'year-round',
    highlights: [
      { highlight: 'Mountain gorilla trekking permit included' },
      { highlight: 'Nyungwe Forest chimpanzee and colobus monkey tracking' },
      { highlight: 'Kigali city tour and Genocide Memorial' },
      { highlight: 'Lake Kivu boat cruise' },
      { highlight: 'Rwanda tea plantation tour' },
      { highlight: 'Experience the cleanest, greenest city in Africa' },
    ],
    faqs: [
      { question: 'How many mountain gorillas are left in the world?', answer: 'There are approximately 1,063 mountain gorillas in the wild, split between the Virunga massif (Rwanda, Uganda, DRC) and Bwindi in Uganda.' },
    ],
    keywords: [
      { keyword: 'Rwanda tour package', searchVolume: 'medium' },
      { keyword: 'Kigali city tour', searchVolume: 'low' },
      { keyword: 'Rwanda gorilla and chimpanzee', searchVolume: 'medium' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '0.8',
      sitemapChangefreq: 'monthly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Rwanda Complete Tour', url: '/tours/6-day-rwanda-gorillas-tea-plantations-kigali' },
      ],
    },
  },
  {
    title: '7-Day Kenya Family Safari – Maasai Mara & Diani Beach',
    slug: '7-day-kenya-family-safari-maasai-mara-diani-beach',
    shortDescription: 'The perfect Kenya family holiday: combine exciting Maasai Mara wildlife safaris with relaxing days on Diani Beach\'s kid-friendly shores. Suitable for children from age 5.',
    tourType: 'family-safari',
    countries: ['kenya'],
    duration: 7,
    price: { amount: 2800, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 3, max: 8 },
    difficulty: 'easy',
    bestTime: 'July to October, December to January',
    isFeatured: false,
    isPopular: false,
    availability: 'year-round',
    highlights: [
      { highlight: 'Child-friendly Maasai Mara game drives' },
      { highlight: 'Diani Beach – Kenya\'s most family-friendly beach' },
      { highlight: 'Junior ranger programs and bush walks' },
      { highlight: 'Maasai village visit with cultural workshops' },
      { highlight: 'Family-sized 4x4 vehicle with pop-up roof' },
      { highlight: 'Snorkeling and beach activities for kids' },
    ],
    faqs: [
      { question: 'What is the minimum age for a Kenya safari?', answer: 'Most Kenya national parks allow children from age 5. Some private conservancies accept younger children. We tailor activities to be age-appropriate and exciting for all family members.' },
    ],
    keywords: [
      { keyword: 'Kenya family safari', searchVolume: 'medium' },
      { keyword: 'family safari East Africa', searchVolume: 'medium' },
      { keyword: 'Diani beach family holiday', searchVolume: 'medium' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '0.8',
      sitemapChangefreq: 'monthly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Kenya Family Safari', url: '/tours/7-day-kenya-family-safari-maasai-mara-diani-beach' },
      ],
    },
  },
  {
    title: '3-Day Nairobi City Safari & Nairobi National Park Tour',
    slug: '3-day-nairobi-city-safari-national-park-tour',
    shortDescription: 'Experience Nairobi – the world\'s only capital city with a national park. See lions and rhinos with the city skyline in the background, visit the David Sheldrick Elephant Orphanage and Karen Blixen Museum.',
    tourType: 'wildlife-safari',
    countries: ['kenya'],
    duration: 3,
    price: { amount: 650, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 1, max: 8 },
    difficulty: 'easy',
    bestTime: 'Year-round',
    isFeatured: false,
    isPopular: false,
    availability: 'year-round',
    highlights: [
      { highlight: 'Nairobi National Park – game drive with city skyline backdrop' },
      { highlight: 'David Sheldrick Elephant Orphanage – feed baby elephants' },
      { highlight: 'Giraffe Centre – hand-feed Rothschild giraffes' },
      { highlight: 'Karen Blixen Museum (Out of Africa)' },
      { highlight: 'Kazuri Beads factory – social enterprise tour' },
      { highlight: 'Bomas of Kenya – traditional cultural performances' },
    ],
    faqs: [
      { question: 'Is Nairobi worth visiting as a tourist?', answer: 'Absolutely. Nairobi is one of Africa\'s most dynamic cities with world-class restaurants, vibrant arts scene, and unique wildlife experiences. It\'s the perfect start or end for your East Africa trip.' },
    ],
    keywords: [
      { keyword: 'Nairobi safari', searchVolume: 'medium' },
      { keyword: 'Nairobi National Park tour', searchVolume: 'medium' },
      { keyword: 'things to do Nairobi', searchVolume: 'high' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '0.7',
      sitemapChangefreq: 'monthly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Nairobi City Safari', url: '/tours/3-day-nairobi-city-safari-national-park-tour' },
      ],
    },
  },
  {
    title: '7-Day Uganda White Water Rafting & Bwindi Gorilla Trek',
    slug: '7-day-uganda-white-water-rafting-bwindi-gorilla',
    shortDescription: 'Uganda\'s most thrilling adventure: conquer the mighty Nile rapids at Jinja – Africa\'s best white water rafting – then trek into Bwindi Forest to encounter mountain gorillas.',
    tourType: 'adventure',
    countries: ['uganda'],
    duration: 7,
    price: { amount: 2900, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 2, max: 8 },
    difficulty: 'challenging',
    bestTime: 'June to September, December to February',
    isFeatured: false,
    isPopular: false,
    availability: 'year-round',
    highlights: [
      { highlight: 'Grade 5 white water rafting on the River Nile at Jinja' },
      { highlight: 'Mountain gorilla trekking in Bwindi Impenetrable Forest' },
      { highlight: 'Boda-boda cycling on Nile source trails' },
      { highlight: 'Quad biking and kayaking at Jinja Adventure Hub' },
      { highlight: 'Kampala city tour and Kasubi Royal Tombs' },
      { highlight: 'Reweta Community Forest walk' },
    ],
    faqs: [
      { question: 'Do I need rafting experience?', answer: 'No previous rafting experience is needed. Our Grade 5 rapids are run with expert guides and full safety equipment. There are calmer sections for less adventurous participants.' },
    ],
    keywords: [
      { keyword: 'Uganda white water rafting', searchVolume: 'medium' },
      { keyword: 'Jinja River Nile rafting', searchVolume: 'medium' },
      { keyword: 'Uganda adventure tour', searchVolume: 'low' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '0.8',
      sitemapChangefreq: 'monthly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Uganda Rafting & Gorilla Trek', url: '/tours/7-day-uganda-white-water-rafting-bwindi-gorilla' },
      ],
    },
  },
  {
    title: '10-Day Kenya Birding Safari – Rift Valley & Coast',
    slug: '10-day-kenya-birding-safari-rift-valley-coast',
    shortDescription: 'Kenya is Africa\'s top birding destination with 1,100+ species. This expert-guided birding safari covers the Rift Valley lakes, Arabuko-Sokoke forest, and the Kenyan coast – a twitcher\'s paradise.',
    tourType: 'birding',
    countries: ['kenya'],
    duration: 10,
    price: { amount: 2700, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 2, max: 8 },
    difficulty: 'easy',
    bestTime: 'November to April',
    isFeatured: false,
    isPopular: false,
    availability: 'year-round',
    highlights: [
      { highlight: 'Lake Bogoria flamingos – up to 2 million birds' },
      { highlight: 'Arabuko-Sokoke Forest – rare coastal forest birds' },
      { highlight: 'Kakamega Rainforest – western Uganda border species' },
      { highlight: 'Maasai Mara savanna raptors and ostriches' },
      { highlight: 'Expert ornithologist guide' },
      { highlight: 'Big Day lists of 200+ species' },
    ],
    faqs: [
      { question: 'How many bird species can I expect to see?', answer: 'On a 10-day birding safari, experienced guides typically record 400-600 species across different ecosystems, often including rare and endemic species.' },
    ],
    keywords: [
      { keyword: 'Kenya birding safari', searchVolume: 'medium' },
      { keyword: 'East Africa birdwatching tour', searchVolume: 'low' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '0.7',
      sitemapChangefreq: 'monthly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Kenya Birding Safari', url: '/tours/10-day-kenya-birding-safari-rift-valley-coast' },
      ],
    },
  },
  {
    title: '10-Day Tanzania Southern Circuit – Ruaha & Selous Safari',
    slug: '10-day-tanzania-ruaha-selous-southern-circuit-safari',
    shortDescription: 'Escape the crowds on Tanzania\'s remote Southern Circuit. Ruaha National Park hosts Tanzania\'s largest elephant and lion populations. Selous (Nyerere) Game Reserve is Africa\'s largest protected area.',
    tourType: 'wildlife-safari',
    countries: ['tanzania'],
    duration: 10,
    price: { amount: 4200, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 2, max: 6 },
    difficulty: 'easy',
    bestTime: 'June to October',
    isFeatured: false,
    isPopular: false,
    availability: 'jun-sep',
    highlights: [
      { highlight: 'Ruaha National Park – Tanzania\'s largest, least visited' },
      { highlight: 'Selous Game Reserve – Africa\'s largest protected wilderness' },
      { highlight: 'Walking safaris in remote wilderness' },
      { highlight: 'Boat safaris on the Rufiji River in Selous' },
      { highlight: 'Rarely seen wild dog packs' },
      { highlight: '95% of this is UNESCO World Heritage Site' },
    ],
    faqs: [
      { question: 'What makes the Southern Circuit different from the Northern?', answer: 'The Southern Circuit is far less crowded and offers a more authentic wilderness experience. Ruaha has Tanzania\'s largest elephant population and some of the best lion viewing in Africa.' },
    ],
    keywords: [
      { keyword: 'Tanzania Southern Circuit safari', searchVolume: 'medium' },
      { keyword: 'Ruaha National Park safari', searchVolume: 'medium' },
      { keyword: 'Selous Game Reserve tour', searchVolume: 'medium' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '0.8',
      sitemapChangefreq: 'monthly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Tanzania Southern Circuit', url: '/tours/10-day-tanzania-ruaha-selous-southern-circuit-safari' },
      ],
    },
  },
  {
    title: '8-Day Kenya Honeymoon Safari & Diani Beach',
    slug: '8-day-kenya-honeymoon-safari-diani-beach',
    shortDescription: 'The most romantic Kenya honeymoon: private game drives in the Maasai Mara, champagne sundowners overlooking the savanna, then 4 nights of pure bliss at a luxury Diani Beach resort.',
    tourType: 'honeymoon',
    countries: ['kenya'],
    duration: 8,
    price: { amount: 4200, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 2, max: 2 },
    difficulty: 'easy',
    bestTime: 'July to October, December to February',
    isFeatured: false,
    isPopular: false,
    availability: 'year-round',
    highlights: [
      { highlight: 'Private game drives – just the two of you' },
      { highlight: 'Champagne bush breakfast in the Mara' },
      { highlight: 'Couples massage in the bush spa' },
      { highlight: 'Diani Beach luxury resort with ocean view villa' },
      { highlight: 'Sunset dhow cruise with private dinner' },
      { highlight: 'Rose petals, strawberries & anniversary setup' },
    ],
    faqs: [
      { question: 'Is Kenya good for a honeymoon?', answer: 'Kenya is one of the world\'s top honeymoon destinations. The combination of incredible wildlife, luxury camps, and beautiful beaches makes it uniquely romantic and unforgettable.' },
    ],
    keywords: [
      { keyword: 'Kenya honeymoon safari', searchVolume: 'high' },
      { keyword: 'Africa honeymoon packages', searchVolume: 'high' },
      { keyword: 'romantic safari Kenya', searchVolume: 'medium' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '0.9',
      sitemapChangefreq: 'weekly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Kenya Honeymoon Safari', url: '/tours/8-day-kenya-honeymoon-safari-diani-beach' },
      ],
    },
  },
  {
    title: '4-Day Budget Kenya Safari – Naivasha & Nakuru',
    slug: '4-day-budget-kenya-safari-naivasha-nakuru',
    shortDescription: 'Affordable Kenya safari without compromising on wildlife. Lake Naivasha boat rides with hippos, Hell\'s Gate cycling, and Lake Nakuru\'s pink flamingos and rhinos – all on a tight budget.',
    tourType: 'budget-safari',
    countries: ['kenya'],
    duration: 4,
    price: { amount: 780, currency: 'USD', priceType: 'per-person' },
    groupSize: { min: 2, max: 12 },
    difficulty: 'easy',
    bestTime: 'Year-round',
    isFeatured: false,
    isPopular: false,
    availability: 'year-round',
    highlights: [
      { highlight: 'Lake Naivasha boat ride with hippos and 350+ bird species' },
      { highlight: 'Hell\'s Gate National Park cycling among geothermal steam' },
      { highlight: 'Lake Nakuru rhinos and flamingos' },
      { highlight: 'Ol Pejeta Conservancy – last two northern white rhinos' },
      { highlight: 'Budget-friendly shared 4x4 vehicle' },
    ],
    faqs: [
      { question: 'Is this the cheapest way to see Kenya\'s wildlife?', answer: 'Yes! This itinerary visits national parks within 3 hours of Nairobi, reducing transport costs. Shared vehicle and mid-range accommodation keeps costs low while delivering exceptional wildlife experiences.' },
    ],
    keywords: [
      { keyword: 'budget Kenya safari', searchVolume: 'medium' },
      { keyword: 'cheap Kenya safari packages', searchVolume: 'high' },
      { keyword: 'affordable African safari', searchVolume: 'high' },
    ],
    indexingConfig: {
      robotsDirective: 'index,follow',
      sitemapPriority: '0.8',
      sitemapChangefreq: 'monthly',
      structuredDataTypes: ['TouristTrip', 'FAQPage', 'BreadcrumbList'],
      breadcrumbs: [
        { label: 'Home', url: '/' },
        { label: 'Tours', url: '/tours' },
        { label: 'Budget Kenya Safari', url: '/tours/4-day-budget-kenya-safari-naivasha-nakuru' },
      ],
    },
  },
]

export async function seedTours(payload: Payload) {
  console.log('Seeding East Africa tours...')
  for (const tour of toursData) {
    const existing = await payload.find({
      collection: 'tours',
      where: { slug: { equals: tour.slug } },
    })
    if (existing.totalDocs === 0) {
      await payload.create({
        collection: 'tours',
        data: {
          ...tour,
          _status: 'published',
          publishedAt: new Date().toISOString(),
          meta: {
            title: `${tour.title} | Safari Trails Africa`,
            description: tour.shortDescription,
          },
        },
      })
      console.log(`✅ Created: ${tour.title}`)
    } else {
      console.log(`⏭️  Skipped (exists): ${tour.title}`)
    }
  }
  console.log('✅ Tours seeding complete!')
}
